container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get github.com/wneessen/sotbot/cmd/sotbot
  build_script: go build github.com/wneessen/sotbot/cmd/sotbot
  test_script: go test github.com/wneessen/sotbot/cmd/sotbot